/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplitRouteImport } from './routes/split'
import { Route as RotateRouteImport } from './routes/rotate'
import { Route as PageNumbersRouteImport } from './routes/page-numbers'
import { Route as MergeRouteImport } from './routes/merge'
import { Route as ConvertRouteImport } from './routes/convert'
import { Route as CompressRouteImport } from './routes/compress'
import { Route as IndexRouteImport } from './routes/index'

const SplitRoute = SplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => rootRouteImport,
} as any)
const RotateRoute = RotateRouteImport.update({
  id: '/rotate',
  path: '/rotate',
  getParentRoute: () => rootRouteImport,
} as any)
const PageNumbersRoute = PageNumbersRouteImport.update({
  id: '/page-numbers',
  path: '/page-numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const MergeRoute = MergeRouteImport.update({
  id: '/merge',
  path: '/merge',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertRoute = ConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressRoute = CompressRouteImport.update({
  id: '/compress',
  path: '/compress',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compress': typeof CompressRoute
  '/convert': typeof ConvertRoute
  '/merge': typeof MergeRoute
  '/page-numbers': typeof PageNumbersRoute
  '/rotate': typeof RotateRoute
  '/split': typeof SplitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compress': typeof CompressRoute
  '/convert': typeof ConvertRoute
  '/merge': typeof MergeRoute
  '/page-numbers': typeof PageNumbersRoute
  '/rotate': typeof RotateRoute
  '/split': typeof SplitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compress': typeof CompressRoute
  '/convert': typeof ConvertRoute
  '/merge': typeof MergeRoute
  '/page-numbers': typeof PageNumbersRoute
  '/rotate': typeof RotateRoute
  '/split': typeof SplitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compress'
    | '/convert'
    | '/merge'
    | '/page-numbers'
    | '/rotate'
    | '/split'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compress'
    | '/convert'
    | '/merge'
    | '/page-numbers'
    | '/rotate'
    | '/split'
  id:
    | '__root__'
    | '/'
    | '/compress'
    | '/convert'
    | '/merge'
    | '/page-numbers'
    | '/rotate'
    | '/split'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompressRoute: typeof CompressRoute
  ConvertRoute: typeof ConvertRoute
  MergeRoute: typeof MergeRoute
  PageNumbersRoute: typeof PageNumbersRoute
  RotateRoute: typeof RotateRoute
  SplitRoute: typeof SplitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/split': {
      id: '/split'
      path: '/split'
      fullPath: '/split'
      preLoaderRoute: typeof SplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotate': {
      id: '/rotate'
      path: '/rotate'
      fullPath: '/rotate'
      preLoaderRoute: typeof RotateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page-numbers': {
      id: '/page-numbers'
      path: '/page-numbers'
      fullPath: '/page-numbers'
      preLoaderRoute: typeof PageNumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge': {
      id: '/merge'
      path: '/merge'
      fullPath: '/merge'
      preLoaderRoute: typeof MergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert': {
      id: '/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress': {
      id: '/compress'
      path: '/compress'
      fullPath: '/compress'
      preLoaderRoute: typeof CompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompressRoute: CompressRoute,
  ConvertRoute: ConvertRoute,
  MergeRoute: MergeRoute,
  PageNumbersRoute: PageNumbersRoute,
  RotateRoute: RotateRoute,
  SplitRoute: SplitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
